version: '3'
services:

  seed:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: seed
    ports:
      - "10762:10762"
    networks:
      - my-network

  client:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: client
    ports:
      - "10763:10762"
    networks:
      - my-network
    depends_on:
      - "seed"

networks:
  my-network:
    driver: bridge